# organize configuration file
# https://organize.readthedocs.io

rules:
  - name: Sort photos & videos into year/month
    locations:
      - /Volumes/MDR/Photos
    filters:
      - created
      - extension:
          - jpg
          - jpeg
          - png
          - heic
          - mov
          - mp4
          - m4v
          - avi
          - mkv
    actions:
      - move: "/Volumes/MDR/Photos/{created.year}/{'{:02d}'.format(created.month)}/"
